### ISSUE TITLE
Legend width varies between clients

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-webview#146]
Especially in the first screenshot, this is not usable.

![image](https://user-images.githubusercontent.com/130405/161738995-0cddfab1-ac48-456c-ab3a-30c1dd5e8089.png)
![image](https://user-images.githubusercontent.com/130405/161739005-4e3a0846-afcd-4687-b4d3-dc5887ac9406.png)
![image](https://user-images.githubusercontent.com/130405/161739016-df922570-9d14-45b7-acf7-0dce485e03b0.png)

**Comment by kinnarr** [comment]
A quick fix could be changing the [maxWidthPercent](https://github.com/metricq/metricq-webview/blob/master/src/MetricQWebView.js#L311)

**Comment by bmario** [comment]
The culprit is probably found here: https://github.com/metricq/metricq-webview/issues/146

Actually, this looks like a code smell and should be done solely in CSS.

**Comment by Quimoniz** [comment]
> The culprit is probably found here: https://github.com/metricq/metricq-webview/blob/master/src/MetricQWebView.js#L306-L330
> 
> Actually, this looks like a code smell and should be done solely in CSS.

Probably the basic issue can be done without much hassle (but it will of course require some manual editing):

Remove like 99 % of all `element.style.cssAttributeHere="someCSSValue"` assignments in javascript (e.g. in [interact.js](https://github.com/metricq/metricq-webview/blob/master/src/interact.js#L453)).

Which files and which code lines are affected can be easily determined by running a grep command like `grep --color=always --recursive --ignore-case --line-number "\\.style"` or to omit the the library and minified files prepend it with a find&xargs combination like with this here `find -type f -iname "*.js" \! -iname "*.min.js" \! -ipath "*/lib/*" | xargs  grep --color=always --recursive --ignore-case --line-number "\\.style"`.

Instead use `element.setAttribute("class","some-css-class-here")` or better yet the more elegant `element.classList.add("some-css-class-here")` ([supported in Firefox since 2010, and in Chrome since 2012](https://developer.mozilla.org/en-US/docs/web/api/element/classlist#browser_compatibility)) whereaver applicable.

If I am asking too much here, please tell me, and I will do it myself.
