### ISSUE TITLE
Autorange breaks when min==max

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-webview#174]
Especially "Lokales Min/Max" will mess up completely when min==max.

- local min/max with `min==max`
- global min/max with `min==max`

should both use
```
min = (1-x) * min
max = (1+x) * min
```
With something like `x = 0.05`

Possibly we even want some buffer like this for `min != max`, but then it should be based on `x * (max - min)`, but that would be  for a different issue.

Setting `min == max` manually should be prevented

**Comment by Quimoniz** [comment]
Thank you very much for looking into the underlying problem tilsche. I couldn't help commiting a little fix to address this issue.

> With something like x = 0.05

The original code used the multipliers (1 + 0.04) and (1 - 0.08) respectively. I retained this decision - but using 0.05 uniformly as is already being used for [whenever there is an y-axis update](https://github.com/metricq/metricq-webview/blob/master/src/MetricHandler.js#L175) with [setPlotRanges()](https://github.com/metricq/metricq-webview/blob/master/src/MetricQWebView.js#L103) makes more sense to me.

Idee for refactoring: maybe we should just unify it, separating this logic into a separate function which both places could use to calculate the 'wiggle room' for the actual visual display/rendering of metrics.

> Possibly we even want some buffer like this for min != max, but then it should be based on x * (max - min)

I am strongly in favor of this, as for what I understand that is in accordance with the original source code where the 'wiggle room' multiplier is also based on the same delta for both min and max. I think I implemented this in https://github.com/metricq/metricq-webview/commit/740d0db1d441147b8f8e7024aac3603e3e5ca742 using the variable name `deltaRange` in that place.

---
:warning: Note: The fix for "a long standing oddity", i.e. that graphs for value ranges 0...123 would actually be drawn between the values −9.84 and 127.92, where now instead they are being drawn between 0 and 137.76 (4 percent + 8 percent =+12 percent), might give rise to surprise to people who got used to the rendering of the y-axis' grid in the past.

**Comment by tilsche** [comment]
I wasn't aware of the current padding mechanism that can just be extended :+1: .

I'm not gonna fight over the percentage values and I don't care if the line in that case is in the middle, 2/3, or the golden ratio.

However, I would not use a fixed arbitrary dimensional value (10). That will get awkward for very small and possibly even very large values. We could use something like `0.1 * max(abs(valueRange[0], abs(valueRange[1]))`

Not quite happy with all those magic numbers,  maybe those should be at least descriptive `const`s in the beginning of the function. Tweaking goal would be that it harmonizes properly with scale computation.

P.S. I sure hope JS does have `Math.max` ;-)?

**Comment by bmario** [comment]
This is still a thing? :crying_cat_face:

**Comment by tilsche** [comment]
Sorry for my missing response.

> Instead of an arbitrary minimum value for the Delta we can use a non-arbitrary value, like Math.pow(10,-323) (0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001) which was the smallest possible exponent that was not cast to Zero in my JavaScript console. Perhaps we would like to use a slighlty higher minimum value, for the purpose of our pixel calculations, by say a factor of one million, so I propose a minimum delta value of Math.pow(10,-317).

Not exactly sure how you want to use that "`ABSOLUTE_EPSILON`". You have to consider that you cannot add that to a "normal value" due to  `1 === Math.pow(10,-317) + 1`

> The proportional 'wiggle room' we calculate could then be equal in both the maximum as well as the minimum direction, thereby reducing the need fo a fixed constant for the wiggle room to just one constant, which is readily available in [MetricHandler.WIGGLEROOM_PERCENTAGE](https://github.com/metricq/metricq-webview/blob/master/src/MetricHandler.js#L18).

Overall we have three cases, and I would suggest to

1) `min != max`

Plot from `min - range * WIGGLE` to  `max + range * WIGGLE`

1) `min == max != 0`

Plot from `min - abs(min) * WIGGLE` to `max + abs(max) * WIGGLE`

2) `min == max == 0`

Here it doesn't really matter, but to get a sensible grid, I would just plot from `-1` to `1` (and yes I'm aware those are arbitrary - but that's only for the special case).

**Comment by tilsche** [comment]
*bump* this is really pants on fire....

**Comment by Quimoniz** [comment]
I tried to address the concerns brought forward by @bmario in the [Pull Request](https://github.com/metricq/metricq-webview/pull/188).   I usually feel very uncomfortable in nagging people about merging pull request. So I won't be nagging Mario much about merging it.
